### ISSUE TITLE
same mobo, i3 12100f error to start

### ISSUE THREAD

**Issue by martin1910jr** [laggykiller/Hackintosh_MSI_B660M-A_WIFI_DDR4#7] opened 2024-03-02 00:22 UTC
hello friend, i try install any version. i found your thread with the same mobo, download the efi, boot two usb, kingston & pny, both load the selector hard disk or usb. hdd with windows and one usb orange colour, select the usb and does nothing

questions. your efi is for 12700k, 

I must change any code for the processor?? 
i must route the usb for the read, later load the usb in the boot??

i try change the name mac pro to imac, try add pci express value without result

sorry for my english, on my language scarce tutorials for this installation. 

![Imagen de WhatsApp 2024-03-01 a las 16 30 20_9ab990a1](https://github.com/laggykiller/Hackintosh_MSI_B660M-A_WIFI_DDR4/assets/161900908/0bb9316a-e45c-46f4-8b0c-416f383626e7)

in this image, only load the windows hdd. any suggestion

**Comment by laggykiller** [comment] 2024-03-02 06:23
> your efi is for 12700k

You have misread. My CPU is 12700F. Both 12700F and 12100F don't have iGPU (Code ending in F means no iGPU), so it is not necessary to disable iGPU. In other words, I don't think you need to change anything due to different processor.

---

You need to be more specific with your wordings.

> any version

What version of macOS? This repository assume you are installing Monterey or above. If not, remove BluetoolFixup.kext

> select the usb and does nothing

What do you mean by does nothing? Any text on the screen? Screen turns black? Screen stays on boot select screen?

---

My best guess is perhaps you just copied the EFI without creating macOS installer itself? You should had used something like `macrecovery.py`. EDIT: Seems like you just copied the downloaded macOS installer dmg file to the USB (The middle icon)? You should read Dortania guide more carefully.

But most importantly, just copying the EFI would not work. **Read the README page and Dortania OpenCore Install Guide**, it listed out all the key things you need to do. Come back after you have followed all instruction. **Record down all the things you have changed to the EFI.** You also need to list out all the hardware you are using

**Comment by laggykiller** [comment] 2024-03-04 05:54
Closing for no reply and not a bug.

**Closed as not planned by laggykiller** 2024-03-04 05:54 UTC
